// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzcFw4Kwx3z7aF8Ur1tP553NYk_6Qm-A',
    appId: '1:524289257900:web:973f15be83d430bde0ca09',
    messagingSenderId: '524289257900',
    projectId: 'flutternotification-a9252',
    authDomain: 'flutternotification-a9252.firebaseapp.com',
    storageBucket: 'flutternotification-a9252.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXg1b821HsEbyuo2NX2ptOnU3njdo_1ts',
    appId: '1:524289257900:android:1b1bf0d99299c9dfe0ca09',
    messagingSenderId: '524289257900',
    projectId: 'flutternotification-a9252',
    storageBucket: 'flutternotification-a9252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwc7S0uiVWXcYNMj1IrTxSGTMbmGWEmq0',
    appId: '1:524289257900:ios:638392b0a222e447e0ca09',
    messagingSenderId: '524289257900',
    projectId: 'flutternotification-a9252',
    storageBucket: 'flutternotification-a9252.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwc7S0uiVWXcYNMj1IrTxSGTMbmGWEmq0',
    appId: '1:524289257900:ios:638392b0a222e447e0ca09',
    messagingSenderId: '524289257900',
    projectId: 'flutternotification-a9252',
    storageBucket: 'flutternotification-a9252.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuzcFw4Kwx3z7aF8Ur1tP553NYk_6Qm-A',
    appId: '1:524289257900:web:4df68f8c1334341ee0ca09',
    messagingSenderId: '524289257900',
    projectId: 'flutternotification-a9252',
    authDomain: 'flutternotification-a9252.firebaseapp.com',
    storageBucket: 'flutternotification-a9252.firebasestorage.app',
  );
}
