import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // 👈 Auto-generated by flutterfire configure
import 'screens/splash_screens.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const TurnoverApp());
}

class TurnoverApp extends StatelessWidget {
  const TurnoverApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Turnover',
      debugShowCheckedModeBanner: false,
      home: SplashScreen(),
    );
  }
}
